config/routes.rb
Rails.application.routes.draw do
  resources :notams

  resources :time_tables 

  root 'time_tables#index'

end

app/models/notam.rb
class Notam < ActiveRecord::Base
end

app/models/time_table.rb
class TimeTable < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notams_controller.rb
class NotamsController < ApplicationController
  before_action :set_notam, only: [:show, :edit, :update, :destroy]

  # GET /notams
  # GET /notams.json
  def index
    @notams = Notam.all
  end

  # GET /notams/1
  # GET /notams/1.json
  def show
  end

  # GET /notams/new
  def new
    @notam = Notam.new
  end

  # GET /notams/1/edit
  def edit
  end
  # METHOD  for collecting day and putting them in right order 
  def create_time_table(time_table, day, r)
    flat_r = r.flatten
    case day
    when "MON" 
      time_table.day1 = flat_r.join(',') 
    when "TUE"
      time_table.day2 = flat_r.join(',')
    when "WED"
      time_table.day3 = flat_r.join(',')
    when "THU"
      time_table.day4 = flat_r.join(',')
    when "FRI"
      time_table.day5 = flat_r.join(',')
    when "SAT"
      time_table.day6 = flat_r.join(',')
    when "SUN"
      time_table.day7 = flat_r.join(',')
    end
  end

  # POST /notams
  # POST /notams.json
  def create
    my_notam = notam_params[:notam_value]
    # Define Days
    days = [ "MON" , "TUE" , "WED" , "THU" , "FRI" , "SAT" , "SUN" ]
    # Get All NOTAMS
    all_notams = my_notam.scan(/A[)]([\s\S]*?)CREATED/)
    all_notams.each do |notam|
      # Get ICAO code form notam 
      icao_code = notam[0].scan(/\s([\s\S]*?)\sB[)]/)
      icao_code_flatten = icao_code.flatten
      time_table = TimeTable.new(icao_code: icao_code_flatten.join(','));
      # Clear all_notams from formatings
      datas = notam[0].gsub(/\r\n|\r|\n/," ")
      # Find Hours in ranges
      days.each_with_index do |day, index|
        days.each_with_index do |day2, index2|
          range2 = datas.scan(/#{day}-#{day2}\s(\d{4}-\d{4})/)
          if range2.empty? == false
            range2.each do |r|
              (index..index2).each do |d|
                create_time_table(time_table, days[d], r)
              end
            end
          end
          range3 = datas.scan(/#{day}-#{day2}[(\s\S)](\d{4}-\d{4},\s\d{4}-\d{4})/)
          if range3.empty? == false
            range3.each do |r|
              (index..index2).each do |d|
                create_time_table(time_table, days[d], r)
              end
            end
          end
        end
        # Find daily working hours
        i1 = datas.scan(/\s#{day}[(\s\S){0,2}](\d{4}-\d{4})\s/)
        i2 = datas.scan(/\s#{day}[(\s\S){0,2}](\d{4}-\d{4},\s\d{4}-\d{4})/)
        i3 = datas.scan(/\s#{day}[(\s\S){0,2}](\d{4}-\d{4},\s\d{4}-\d{4},\s\d{4}-\d{4})/)
        i4 = datas.scan(/\s#{day}[(\s\S){0,2}](\d{4}-\d{4},\s\d{4}-\d{4},\s\d{4}-\d{4},\s\d{4}-\d{4})/)
        ic = datas.scan(/\s#{day}[(\s\S){0,2}](CLOSED)/)
        ic2 = datas.scan(/\s#{day}[(\s\S){0,2}](CLSD)/)
        create_time_table(time_table, day, i1) if i1.present? || i1.nil?
        create_time_table(time_table, day, i2) if i2.present? || i2.nil? 
        create_time_table(time_table, day, i3) if i3.present? || i3.nil?
        create_time_table(time_table, day, i4) if i4.present? || i4.nil?
        create_time_table(time_table, day, [[ic]]) if ic.present? || ic.nil?
        create_time_table(time_table, day, [["CLOSED"]]) if ic2.present? || ic2.nil?
      end
      # write data
      time_table.save!
    end
    redirect_to time_tables_path
  end

  # PATCH/PUT /notams/1
  # PATCH/PUT /notams/1.json
  def update
    respond_to do |format|
      if @notam.update(notam_params)
        format.html { redirect_to @notam, notice: 'Notam was successfully updated.' }
        format.json { render :show, status: :ok, location: @notam }
      else
        format.html { render :edit }
        format.json { render json: @notam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notams/1
  # DELETE /notams/1.json
  def destroy
    @notam.destroy
    respond_to do |format|
      format.html { redirect_to notams_url, notice: 'Notam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notam
      @notam = Notam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notam_params
      params.require(:notam).permit(:notam_value)
    end
end

app/controllers/time_tables_controller.rb
class TimeTablesController < ApplicationController
  before_action :set_time_table, only: [:show, :edit, :update, :destroy]

  # GET /time_tables
  # GET /time_tables.json
  def index
    @time_tables = TimeTable.all
  end

  # GET /time_tables/1
  # GET /time_tables/1.json
  def show
  end

  # GET /time_tables/new
  def new
    @time_table = TimeTable.new
  end

  # GET /time_tables/1/edit
  def edit
  end


  # POST /time_tables
  # POST /time_tables.json
  def create
    @time_table = TimeTable.new(time_table_params)

    respond_to do |format|
      if @time_table.save
        format.html { redirect_to @time_table, notice: 'Time table was successfully created.' }
        format.json { render :show, status: :created, location: @time_table }
      else
        format.html { render :new }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_tables/1
  # PATCH/PUT /time_tables/1.json
  def update
    respond_to do |format|
      if @time_table.update(time_table_params)
        format.html { redirect_to @time_table, notice: 'Time table was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_table }
      else
        format.html { render :edit }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_tables/1
  # DELETE /time_tables/1.json
  def destroy
    @time_table.destroy
    respond_to do |format|
      format.html { redirect_to time_tables_url, notice: 'Time table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_table
      @time_table = TimeTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_table_params
      params.require(:time_table).permit(:icao_code, :day1, :day2, :day3, :day4, :day5, :day6, :day7)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StatajetExam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notams/_form.html.erb
<%= form_for(@notam) do |f| %>
  <% if @notam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notam.errors.count, "error") %> prohibited this notam from being saved:</h2>

      <ul>
      <% @notam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notam_value %><br>
    <%= f.text_area :notam_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notams/edit.html.erb
<h1>Editing notam</h1>

<%= render 'form' %>

<%= link_to 'Show', @notam %> |
<%= link_to 'Back', notams_path %>

app/views/notams/index.html.erb
<h1>Listing notams</h1>

<table>
  <thead>
    <tr>
      <th>Notam value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notams.each do |notam| %>
      <tr>
        <td><%= notam.notam_value %></td>
        <td><%= link_to 'Show', notam %></td>
        <td><%= link_to 'Edit', edit_notam_path(notam) %></td>
        <td><%= link_to 'Destroy', notam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notam', new_notam_path %>

app/views/notams/new.html.erb
<h1>New notam</h1>

<%= render 'form' %>

<%= link_to 'Back', notams_path %>

app/views/notams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notam value:</strong>
  <%= @notam.notam_value %>
</p>

<%= link_to 'Edit', edit_notam_path(@notam) %> |
<%= link_to 'Back', notams_path %>

app/views/time_tables/_form.html.erb
<%= form_for(@time_table) do |f| %>
  <% if @time_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_table.errors.count, "error") %> prohibited this time_table from being saved:</h2>

      <ul>
      <% @time_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icao_code %><br>
    <%= f.text_field :icao_code %>
  </div>
  <div class="field">
    <%= f.label :day1 %><br>
    <%= f.text_field :day1 %>
  </div>
  <div class="field">
    <%= f.label :day2 %><br>
    <%= f.text_field :day2 %>
  </div>
  <div class="field">
    <%= f.label :day3 %><br>
    <%= f.text_field :day3 %>
  </div>
  <div class="field">
    <%= f.label :day4 %><br>
    <%= f.text_field :day4 %>
  </div>
  <div class="field">
    <%= f.label :day5 %><br>
    <%= f.text_field :day5 %>
  </div>
  <div class="field">
    <%= f.label :day6 %><br>
    <%= f.text_field :day6 %>
  </div>
  <div class="field">
    <%= f.label :day7 %><br>
    <%= f.text_field :day7 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_tables/edit.html.erb
<h1>Editing time_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_table %> |
<%= link_to 'Back', time_tables_path %>

app/views/time_tables/index.html.erb
<h1>Listing time_tables</h1>

<table>
  <thead>
    <tr>
      <th>Icao code</th>
      <th>Day1</th>
      <th>Day2</th>
      <th>Day3</th>
      <th>Day4</th>
      <th>Day5</th>
      <th>Day6</th>
      <th>Day7</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_tables.each do |time_table| %>
      <tr>
        <td><%= time_table.icao_code %></td>
        <td><%= time_table.day1 %></td>
        <td><%= time_table.day2 %></td>
        <td><%= time_table.day3 %></td>
        <td><%= time_table.day4 %></td>
        <td><%= time_table.day5 %></td>
        <td><%= time_table.day6 %></td>
        <td><%= time_table.day7 %></td>
        <td><%= link_to 'Show', time_table %></td>
        <td><%= link_to 'Edit', edit_time_table_path(time_table) %></td>
        <td><%= link_to 'Destroy', time_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Add New NOTAM DATA', new_notam_path %>
<%= link_to 'New Time table', new_time_table_path %>

app/views/time_tables/new.html.erb
<h1>New time_table</h1>

<%= render 'form' %>

<%= link_to 'Back', time_tables_path %>

app/views/time_tables/parser.html.erb
<h1>New time_table</h1>

<%= form_for(@data) do |f| %>
  <% if @time_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_table.errors.count, "error") %> prohibited this time_table from being saved:</h2>

      <ul>
      <% @time_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :add_txt_file %><br>
    <%= f.text_field :notam_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', time_tables_path %>

app/views/time_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Icao code:</strong>
  <%= @time_table.icao_code %>
</p>

<p>
  <strong>Day1:</strong>
  <%= @time_table.day1 %>
</p>

<p>
  <strong>Day2:</strong>
  <%= @time_table.day2 %>
</p>

<p>
  <strong>Day3:</strong>
  <%= @time_table.day3 %>
</p>

<p>
  <strong>Day4:</strong>
  <%= @time_table.day4 %>
</p>

<p>
  <strong>Day5:</strong>
  <%= @time_table.day5 %>
</p>

<p>
  <strong>Day6:</strong>
  <%= @time_table.day6 %>
</p>

<p>
  <strong>Day7:</strong>
  <%= @time_table.day7 %>
</p>

<%= link_to 'Edit', edit_time_table_path(@time_table) %> |
<%= link_to 'Back', time_tables_path %>